# Gradle properties
org.gradle.jvmargs=-Xmx6G
org.gradle.caching=true
org.gradle.daemon=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
loader_version=0.19.2
fabric_kotlin_version=1.13.11+kotlin.2.3.21

# Mod Properties(Arrange in order of a-z)
mod_archives_base_name= template_kotlin_mod
mod_id=                 template_kotlin_mod
mod_license=            MIT
mod_maven_group=        net.ender.template_kotlin_mod
mod_name=               Template Kotlin Mod
mod_version=            1.0.0

# Dependencies
fabric_api_version=0.116.12+1.21.1